version: '3.7'

services:
  node:
    image: "node:11"
    working_dir: /code
    command: bash -c "npm install && npm start"
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - .:/code

  wordpress:
    volumes:
      - ./public/scripts:/var/www/html/wp-content/themes/ccmclub/scripts
