version: '3.7'

services:
   db:
     image: mysql:5.7
     volumes:
       - db:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: ${PASSWORD}

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "${WEB_PORT}:80"
     restart: always
     volumes:
       - ./web:/var/www/html
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: ${PASSWORD}
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DEBUG: ${DEBUG}

   cli:
     image: wordpress:cli
     user: "33:33"
     depends_on:
       - wordpress
     volumes:
       - ./web:/var/www/html

volumes:
    db:
